# ===== BUILD =====
FROM maven:3.9.6-eclipse-temurin-17 AS build

WORKDIR /app
COPY . .

# Fix Windows CRLF
RUN sed -i 's/\r$//' mvnw
RUN chmod +x mvnw

RUN ./mvnw -DskipTests package

# ===== RUN =====
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080

ENTRYPOINT ["java","-jar","app.jar"]
